Feature/GitHub source
Mikts/Infobserve pull request #15
Opened 2020-10-11 17:39 UTC by Mikts

Add a source for github public events endpoint.

2020-10-11 18:02 UTC, kostaskol requested changes

2020-10-11 18:02 UTC, kostaskol commented on infobserve/sources/github.py
> +        async with aiohttp.ClientSession(headers=headers) as session:
Wait, `headers` must be set both in the session *and* in `session.get`? :open_mouth:

2020-10-11 18:02 UTC, kostaskol commented on infobserve/sources/github.py
> +                github_events = [x for x in github_events if x["type"] == "PushEvent"]
I think it's best to simply loop over `github_events` in a normal for loop and get all the information you need. Currently, it runs through the array twice

2020-10-14 19:17 UTC, Mikts commented on infobserve/processors/yara_processor.py
> +                elif isinstance(event, GithubEvent):
Reworked it by adding a `CommitEvent` class that contains the information of the `GithubEvent` that each file changed belongs to. As an approach overall it works. But we should check to analyze `patch` or `diff` as a different option.

2020-10-15 16:26 UTC, kostaskol reviewed
Nice work, this seems much cleaner now!
Still have a few thoughts but we're nearly there I think!

2020-10-15 16:26 UTC, kostaskol commented on infobserve/events/github.py
> +    """The CommitEvent Class represents a file changed in a commit that belongs to a GitHubEvent"""
So maybe `GithubCommitEvent`? Future proof it a bit for when gitlab commits roll in as well (and then `CommitEvent` could be a parent class or something)

2020-10-15 16:26 UTC, kostaskol commented on infobserve/events/github.py
> +        BaseEvent.__init__(self, github_event.timestamp, source=github_event.source)
`super().__init__(...`

2020-10-15 16:26 UTC, kostaskol commented on infobserve/events/github.py
> +    def __init__(self, github_event: GithubEvent, raw_content: str, filename: str):
It might be due to me not known the github commits API well, but I'd expect a github commit to potentially (and probably) have more than one file

2020-10-15 16:26 UTC, kostaskol commented on infobserve/events/github.py
> +            raw_content (str): The content of the file changed in str.
[...] file changed ~~in str~~ (the type is obvious from `raw_content (str)`)

2020-10-15 16:26 UTC, kostaskol commented on infobserve/processors/yara_processor.py
> +from infobserve.events import ProcessedEvent, GithubEvent
:scissors:

2020-10-15 16:26 UTC, kostaskol commented on infobserve/sources/github.py
> +        _etag(str): Returns no data if no changes detected in the api.
Gitlab has a thing or two to learn from Github :laughing:

2020-10-15 16:26 UTC, kostaskol commented on infobserve/sources/github.py
> +                    event_list.append(ge)
I don't think this needs to be within the `try` block, right?

2020-10-15 16:26 UTC, kostaskol commented on infobserve/sources/github.py
> +            if self._index_cache:
In which cases is `self._index_cache` false?

2020-10-15 16:26 UTC, kostaskol commented on infobserve/sources/github.py
> +            commit_event_list: List[GithubEvent] = [x for x in event.commit_raw_content() for event in event_list]
You're already looping through `event_list` 2 lines above

2020-10-15 16:26 UTC, kostaskol commented on infobserve/sources/github.py
> +                APP_LOGGER.warning("There was an error retrieving the payload will retry in next cycle.")
Does `ClientPayloadError` not contain any useful information? Maybe we could log its message as well?

2020-10-15 17:31 UTC, kostaskol approved these changes

2020-10-15 17:31 UTC, merged